### ISSUE TITLE
Issue with character encoding in About screen

### ISSUE THREAD

**Issue by Soviet666** [rybak/resoday#1]
![bug](https://user-images.githubusercontent.com/759823/144201834-b899c209-858d-4ead-be2a-c5fe5bf69769.jpg)

**Comment by rybak** [comment]
The rendering issues are present, for example, when default encoding is windows-1250 or windows-1252.

I got confused by https://stackoverflow.com/q/8325109/1083697 at first, but it's ok now. I will now know to specify UTF-8 explicitly for HTML content.
